services:
  api:
    build:
      context: ./backend/ProductApi
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "5091:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend       # <- must be the folder where package.json lives
      dockerfile: Dockerfile
    container_name: product-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5091/api
    depends_on:
      - api
